drop database infinitegames6

CREATE DATABASE INFINITEGAMES6

USE INFINITEGAMES6

CREATE TABLE CLIENTE(
COD_CLIENTE INT PRIMARY KEY identity,
NOME_CLIENTE VARCHAR (50),
CPF_CLIENTE VARCHAR (11),
ENDEREÇO_CLIENTE VARCHAR (50),
)

INSERT INTO CLIENTE(NOME_CLIENTE,CPF_CLIENTE,ENDEREÇO_CLIENTE) VALUES('Narutin', '48045398833', 'konoha')

CREATE TABLE FUNCIONARIO(
COD_FUNCIONARIO INT PRIMARY KEY identity,
NOME_FUNCIONARIO VARCHAR (50),
USUARIO_FUNCIONARIO VARCHAR (10),
SENHA_FUNCIONARIO VARCHAR (50)
)

INSERT INTO FUNCIONARIO (NOME_FUNCIONARIO,USUARIO_FUNCIONARIO,SENHA_FUNCIONARIO)
VALUES ('LUAN OLIVEIRA', 'LUAN', '123')

CREATE TABLE PRODUTO(
COD_PRODUTO INT PRIMARY KEY identity,
NOME_PRODUTO VARCHAR (50),
CATEGORIA_PRODUTO VARCHAR (20),
VALOR FLOAT,
QUANTIDADE INT
)

INSERT INTO  PRODUTO(NOME_PRODUTO, CATEGORIA_PRODUTO, VALOR, QUANTIDADE) VALUES('Xbox Series X', 'Console', 4800, 10)
INSERT INTO  PRODUTO(NOME_PRODUTO, CATEGORIA_PRODUTO, VALOR, QUANTIDADE) VALUES('Play Station 5', 'Console', 5000, 10)
INSERT INTO  PRODUTO(NOME_PRODUTO, CATEGORIA_PRODUTO, VALOR, QUANTIDADE) VALUES('The Witcher 3 - PS4', 'Jogo', 80, 100)
INSERT INTO  PRODUTO(NOME_PRODUTO, CATEGORIA_PRODUTO, VALOR, QUANTIDADE) VALUES('Teclado HyperX', 'Periférico', 1200, 40)




CREATE TABLE PEDIDO(
COD_PEDIDO INT PRIMARY KEY identity,
COD_CLIENTE INT,
VALOR FLOAT,
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE),
)

insert into PEDIDO(COD_CLIENTE, VALOR) values(1, 9600)

CREATE TABLE ITENSPEDIDO(
COD_PRODUTO INT,
COD_PEDIDO INT,
NUMERO_ITEM INT,
QUANTIDADE FLOAT,
PRECO FLOAT,
PRIMARY KEY (COD_PEDIDO,NUMERO_ITEM),
FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDO(COD_PEDIDO),
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
)

INSERT INTO ITENSPEDIDO(COD_PRODUTO,NUMERO_ITEM, QUANTIDADE, PRECO) VALUES(1, 1, 2, 9600)
INSERT INTO ITENSPEDIDO(COD_PEDIDO,COD_PRODUTO,NUMERO_ITEM, QUANTIDADE, PRECO) VALUES(2,1, 1, 2, 9600)
INSERT INTO ITENSPEDIDO(COD_PEDIDO,COD_PRODUTO,NUMERO_ITEM, QUANTIDADE, PRECO) VALUES(2,2, 2, 2, 10000)
INSERT INTO ITENSPEDIDO(COD_PEDIDO,COD_PRODUTO,NUMERO_ITEM, QUANTIDADE, PRECO) VALUES(2,3, 3, 2, 160)
INSERT INTO ITENSPEDIDO(COD_PEDIDO,COD_PRODUTO,NUMERO_ITEM, QUANTIDADE, PRECO) VALUES(2,4, 4, 2, 2400)


CREATE TABLE VENDA (
COD_VENDA INT PRIMARY KEY identity,
VALOR_VENDA FLOAT,
FORMA_PAGAMENTO VARCHAR (30),
COD_PEDIDO INT,
COD_CLIENTE INT,
FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDO (COD_PEDIDO),
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE)
)

CREATE TABLE ENTREGA(

COD_ENTREGA INT PRIMARY KEY identity,
ENDEREÇO_CLIENTE VARCHAR (50),
DATA_ENTREGA DATE,
)

CREATE TABLE AGENDA(
COD_AGENDA INT PRIMARY KEY identity,
COD_PRODUTO INT,
COD_CLIENTE INT,
NOME_PRODUTO VARCHAR (50),
DATA_AGENDA DATE,
HORARIO_AGENDA TIME,
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO),
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE),
)

SELECT * FROM CLIENTE
SELECT * FROM FUNCIONARIO
SELECT * FROM ITENSPEDIDO
SELECT * FROM PRODUTO
SELECT * FROM VENDA
SELECT * FROM ENTREGA
SELECT * FROM AGENDA
SELECT * FROM PEDIDO

